name: "CI: Build library and run tests"
on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docker-build-and-test

