name: Continuous Integration
on: push

jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.201'
      - name: Restore and build
        run: |
          dotnet build --configuration Release ./src/Dodo.HttpClientExtensions/Dodo.HttpClientExtensions.csproj
          ls ./src/Dodo.HttpClientExtensions/bin/Release/netstandard2.0
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: Library artifacts
      #     path: ./src/Dodo.HttpClientExtensions/bin/Release/netstandard2.0

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       dotnet: [ '2.2.110', '3.1.201' ]
  #   name: Test library on .NET Core ${{ matrix.dotnet }}
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Setup dotnet
  #       uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: ${{ matrix.dotnet }}
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@master
  #       with:
  #         name: Library artifacts
  #         path: ./src/Dodo.HttpClientExtensions/bin/Release/netstandard2.0
  #     - name: Run tests
  #       run: dotnet test --configuration Release ./src/Dodo.HttpClientExtensions.Tests/Dodo.HttpClientExtensions.Tests.csproj
