name: Continuous Integration
on: push

jobs:
  build:
    name: Build library and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.201'
      - name: Restore and build
        run: |
          dotnet restore ./src/Dodo.HttpClientExtensions/Dodo.HttpClientExtensions.csproj
          dotnet build --no-restore --configuration Release ./src/Dodo.HttpClientExtensions/Dodo.HttpClientExtensions.csproj
          dotnet test --configuration Release ./src/Dodo.HttpClientExtensions.Tests/Dodo.HttpClientExtensions.Tests.csproj
